server:
  port: 9078

spring:
  cloud:
    config:
      server:
        git:
          username: kablumndl546
          password: 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
          clone-on-start: true
          default-label: master
          basedir: /target/edastakhat/config
          search-paths:
          - /edastakhat-deploy/config/*
          uri: https://github.com/mandalorg/edastakhat-deploy.git
          skip-ssl-validation: true
          timeout: 11
  application:
   name: nsdl-edastakhat-conf-service
---         
logging:
  level:
    '[com.nsdl.edustakhat.conf]': debug
    #'[com.nsdl.edustakhat.conf]': debug
    '[com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver]': warn
debug: false
---
logging:
  level:
    root: INFO
---    
eureka:
  instance:
    prefer-ip-address: true
    instanceId: EDUSTAKHAT_CONF_MS:${server.port}
    hostname: ed-registry
 
  client:
    service-url:
     defaultZone: http://nsdl-edastakhat-dis:8081/eureka/
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    
    
    
     